version: 2
updates:
  # Gradle (Kotlin 백엔드) 의존성 설정
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "B-Singularity"
    labels:
      - "dependencies"

  # GitHub Actions 워크플로우 의존성 설정
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"