package execution.domain.vo

/**
 * [Domain Enum] Log Retention Policy
 * Determines the lifecycle of the audit log files generated by the workers.
 */
enum class LogRetention {
    /**
     * [Quiet] No log files are preserved.
     * Useful for CI environments where disk usage is critical and logs are not needed.
     */
    NONE,

    /**
     * [Default] Smart Mode.
     * Log files are preserved ONLY if the test fails.
     * Successful test logs are overwritten by subsequent runs to save disk space.
     */
    ON_FAILURE,

    /**
     * [Verbose] All log files are preserved regardless of the test outcome.
     * Enabled via `--verbose` or `--archive`.
     */
    ALWAYS,
}

/**
 * [Domain Enum] Audit Depth
 * Determines the granularity of the information recorded in the audit log.
 */
enum class AuditDepth {
    /**
     * [Default] Result-Focused.
     * Records only the inputs (Arguments), the outcome (Verdict), and any errors.
     * The internal BDD phases (Design, Mocking details) are omitted to keep files small.
     */
    SIMPLE,

    /**
     * [Trace] Explainable Execution.
     * Records the full BDD lifecycle: Design (Strategy/Mocking) -> Execution -> Verification.
     * Enables "Time-Travel" debugging to understand *why* a specific value was generated.
     */
    EXPLAINABLE,
}
