package execution.port.outgoing

import execution.domain.vo.trace.TraceEvent

/**
 * [Port] Trace Sink (Output Port)
 *
 * Serves as the exit point for exporting Audit Logs generated by the Execution Engine (Core)
 * to external storage (e.g., File System).
 *
 * * **Responsibility**: The Execution Domain requests "Persistence" via this interface without knowing
 * whether the underlying implementation is a local file, a database, or a network stream.
 * * **Scope**: Following [ADR-017], one Sink is assigned per Worker Thread and is reused.
 */
interface TraceSink : AutoCloseable {
    /**
     * Emits a trace event to the underlying stream immediately.
     * This supports the "Streaming WAL" pattern to ensure data safety in case of crashes.
     *
     * @param event The atomic audit event to record (e.g., ExecutionTrace, VerificationTrace).
     */
    fun emit(event: TraceEvent)

    /**
     * Retrieves the absolute path of the current journal file.
     * Used for the [Claim Check] pattern to pass the file location to the reporting system.
     *
     * @return The absolute file path of the active worker log.
     */
    fun getJournalPath(): String

    /**
     * [Opt-in] Snapshots the current log content to a specific target file.
     * This is used to preserve logs for successful tests when the user enables tracing options.
     *
     * @param targetFileName The relative path or filename for the snapshot (e.g., "traces/run-123.log").
     * @return The absolute path of the saved snapshot file.
     */
    fun snapshotTo(targetFileName: String): String

    /**
     * [Rewind] Resets the sink state for the next test execution.
     * This typically involves rewinding the file cursor to the beginning (truncate)
     * and clearing any internal buffers without closing the file handle.
     */
    fun reset()
}
