package execution.domain.vo.plan

import metamodel.domain.vo.TypeReference

/**
 * [Intermediate Representation] Unlinked Node (The Plan)
 *
 * Represents a node in the object graph plan generated by the [execution.domain.service.planner.StructuralPlanner].
 * At this stage, the graph is purely structural and has not yet been assigned specific Generators.
 *
 * ## Architectural Role
 * 1. **Deterministic Structure**: Merges attributes from declaration sites and usage sites using a "Last-Wins" policy.
 * 2. **Cycle Awareness**: Explicitly identifies recursive loops via [UnlinkedCycleNode] (ADR-027).
 * 3. **Tech-Agnostic**: Decoupled from specific runtime mechanisms (Reflection/KSP); relies on pure [TypeReference].
 *
 * @see execution.domain.service.planner.StructuralPlanner
 * @see execution.domain.service.linker.ExpansionLinker
 */
sealed interface UnlinkedNode {
    /**
     * The pure type reference associated with this node.
     */
    val type: TypeReference

    /**
     * Effective attributes merged from all sources (Type Declaration, Field, Usage).
     * Used by the Linker to select the appropriate Generator.
     */
    val attributes: Map<String, Attribute>
}

/**
 * [Cycle Marker] Represents a detected recursive loop in the object graph.
 *
 * This node serves as a "Stop Sign" for the Planner. It contains diagnostic information
 * required by the [execution.domain.strategy.generation.CycleBreakingGenerator] to decide
 * how to safely terminate the recursion (e.g., return null, empty collection, or a proxy stub).
 *
 * @property targetTypeId The cycleId of the ancestor node that is being revisited.
 * @property pathSnapshot A string representation of the traversal path for debugging (e.g., "A -> B -> A").
 * @property edgeKind The relationship type of the edge causing the cycle.
 */
data class UnlinkedCycleNode(
    override val type: TypeReference,
    override val attributes: Map<String, Attribute>,
    val edgeKind: EdgeKind,
    val edgeName: String?,
    val targetTypeId: String,
    val pathSnapshot: String
) : UnlinkedNode

/**
 * [Leaf Node] Represents an atomic value type (e.g., String, Int, UUID, Enum).
 * These nodes do not have children and are handled by SimpleGenerators.
 */
data class UnlinkedAtomicNode(
    override val type: TypeReference,
    override val attributes: Map<String, Attribute>
) : UnlinkedNode

/**
 * [Structural Node] Represents a complex object (Class, Data Class) composed of fields.
 *
 * @property fields A map of field names to their corresponding child plan nodes.
 */
data class UnlinkedCompositeNode(
    override val type: TypeReference,
    val fields: Map<String, UnlinkedNode>,
    override val attributes: Map<String, Attribute>
) : UnlinkedNode

/**
 * [Container Node] Represents a linear collection (List, Set, Array).
 *
 * @property elementNode The plan for the elements contained within this collection.
 * @property isFixedSize True if the container is an Array; false for standard Collections.
 */
data class UnlinkedCollectionNode(
    override val type: TypeReference,
    val elementNode: UnlinkedNode,
    val isFixedSize: Boolean,
    override val attributes: Map<String, Attribute>
) : UnlinkedNode

/**
 * [Dictionary Node] Represents a Key-Value mapping (Map).
 *
 * @property keyNode The plan for the map keys.
 * @property valueNode The plan for the map values.
 */
data class UnlinkedMapNode(
    override val type: TypeReference,
    val keyNode: UnlinkedNode,
    val valueNode: UnlinkedNode,
    override val attributes: Map<String, Attribute>
) : UnlinkedNode